### ISSUE TITLE
[Nox.Generators] Seed Data for Enumeration Types MP-9674

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#1017]
- relates to #988
 
# Seed Default Values

1. When the API starts the Values must be created / updated / delete (name only) by Id in the `<EntityName><AttributeName>` Entity
2. When the API starts the Values must be created / updated / delete by Id in the `<EntityName><AttributeName>Localized` Entity for the Nox.Solution Default Culture Code
3. UnSkipp test `WhenPostWithContinent_ShouldGetContinent`

Do the Seed in the EntityDboContext example: https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding 

# Example

```
 - name: Continent
   description: Country Continent
   type: enumeration
   enumerationTypeOptions:
     values: 
       - { id: 1, name: Europe} 
       - { id: 2, name: Asia}
       - { id: 3, name: Africa} 
       - { id: 4, name: America} 
       - { id: 5, name: Oceania} 
     isLocalized: true
   isRequired: false
```
