### ISSUE TITLE
[Nox.Generator] Allow to create custom resource paths for an entity

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#1045]
1. Allow Yaml (Entity) to configure custom resource paths and translate them to odata query 
2. Create Middleware for the translation
3. Create a Yaml validator and use `ODataQueryValidator`
4. Update Generated Documentation with Custom EndPoints
5. Update swagger to reflect this API / Update Odata Routes
6. Only for Get Verbs

see https://github.com/NoxOrg/Nox.Lib.V6/blob/main/src/Nox.Api/DynamicApiMiddleware.cs and https://github.com/NoxOrg/Nox.Lib.V6/blob/main/src/Nox.Lib/Extensions/ApplicationBuilderExtensions.cs

## Yaml pseudo Example 
Domain:
```
domain:

  entities:

       name: Tenants

       customResourcePaths:
            - resourcePath:
                  path: /Tenants/{tenantKey}/TenantBrandId/{tenantBrandIdkey}/Users/{userId}
                  oDataQuery: $expand=Tenants($filter=Id eq {tenantKey};$expand=TenantBrandId($filter=Id eq {tenantBrandIdkey};$expand=users($filter=id eq {userId})))
                  description: Get users for a Tenant Brand Id
```
