### ISSUE TITLE
[Nox.Generators] [Odata] Manual Test Sample Web App for Post Owned entity

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#611]
for this we can create an End to End Test

**Comment by anna-naumova25** [comment]
### ISSUE 1 No validation for single relatioship with Keys (ZeroOrOne, ExactlyOne)

### Steps to reproduce

1. Add ZeroOrOne relationship to Country entity in SampleWebApp
```
ownedRelationships:
  - name: CountryLocalNameRel
    description: is also know as
    relationship: zeroOrOne
    entity: CountryLocalName
``` 
2. Identify CountryLocalName entity and set Keys for it
```
- name: CountryLocalName
  description: The name of a country in other languages

  persistence:
    isAudited: false

  keys:

    - name: Id
      isRequired: true
      type: databaseNumber

  attributes:
    - name: Name
      isRequired: true
      type: text
      textTypeOptions:
        minLength: 5
        maxLength: 10

    - name: NameCode
      isRequired: false
      type: countryCode2
    
    - name: CustomNumber
      isRequired: false
      type: number
      numberTypeOptions:
       minValue: 100
       maxValue: 1000
```  
### Actual result

- Id added to CountryLocalNameDto
- Therefore Id is displayed in POST /api/Countries
- Id ignored in all the other levels - database, mapper, domain entity
### Expected result
yaml files should be validated so that ZeroOrOne and ExactlyOne OwnedRelationship models does NOT contain Keys

**Comment by anna-naumova25** [comment]
### ISSUE 2 Sigle relationship GET fails (ZeroOrOne, ExactlyOne)

### Steps to reproduce

1. Add ZeroOrOne relationship to Country entity in SampleWebApp
```
ownedRelationships:
  - name: CountryLocalNameRel
    description: is also know as
    relationship: zeroOrOne
    entity: CountryLocalName
``` 
2. Identify CountryLocalName entity
```
- name: CountryLocalName
  description: The name of a country in other languages

  persistence:
    isAudited: false

  attributes:
    - name: Name
      isRequired: true
      type: text
      textTypeOptions:
        minLength: 5
        maxLength: 10

    - name: NameCode
      isRequired: false
      type: countryCode2
    
    - name: CustomNumber
      isRequired: false
      type: number
      numberTypeOptions:
       minValue: 100
       maxValue: 1000
```  
3. GET /api/Countries
### Actual result
Response Code 200
```
can't parse JSON.  Raw result:

{"@odata.context":"https://localhost:7024/api/$metadata#Countries(CountryLocalName())","value":[{"statusCode":500,"message":"Error occured during request: /api/Countries.Error: Invalid object name \u0027CountryLocalName\u0027."}
``` 
### Expected result
Get the list of existing countries

**Comment by anna-naumova25** [comment]
### ISSUE 3 Parent model is created with empty child (ZeroOrOne, ExactlyOne)

### Steps to reproduce

1. Repeat steps 1 and 2 from Issue 2
2. POST /api/Countries
```
{
  "Name": "Name1",
  "FormalName": "FormalName1",
  "AlphaCode3": "MNE",
  "AlphaCode2": "ME",
  "NumericCode": 800,
  "DialingCodes": "DialingCodes11",
  "Capital": "Capital1",
  "Demonym": "Demonym1",
  "AreaInSquareKilometres": 132891.238045,
  "GeoRegion": "qwe",
  "GeoSubRegion": "qwe",
  "GeoWorldRegion": "qwe",
  "Population": 12346,
  "TopLevelDomains": "me",
  "GeoCoord": null,
  "countryLocalName": {
    "name": "cln 1"
  }
}
``` 
### Actual result
Response Code 200
```
{
  "@odata.context": "https://localhost:7024/api/$metadata#Countries/SampleWebApp.Application.Dto.CountryKeyDto/$entity",
  "@odata.type": "#SampleWebApp.Application.Dto.CountryKeyDto",
  "keyId": 8
}
``` 
Country model is created, but CountryLocalName_Name field is NULL in the database
### Expected result
Country with CountryLocalName created successfully

**Comment by anna-naumova25** [comment]
### ISSUE 4

### Steps to reproduce

1. Repeat steps 1 and 2 from Issue 1
2. POST /api/Countries with invalid CountryLocalName model
```
{
  "Name": "Name1",
  "FormalName": "FormalName1",
  "AlphaCode3": "MNE",
  "AlphaCode2": "ME",
  "NumericCode": 800,
  "DialingCodes": "DialingCodes11",
  "Capital": "Capital1",
  "Demonym": "Demonym1",
  "AreaInSquareKilometres": 132891.238045,
  "GeoRegion": "qwe",
  "GeoSubRegion": "qwe",
  "GeoWorldRegion": "qwe",
  "Population": 12346,
  "TopLevelDomains": "me",
  "GeoCoord": null,
  "countryLocalNames": [
    {
      "nameCode": "q"
    }
  ]
}
``` 
### Actual result
Response Code 200
```
{
  "@odata.context": "https://localhost:7024/api/$metadata#Countries/SampleWebApp.Application.Dto.CountryKeyDto/$entity",
  "@odata.type": "#SampleWebApp.Application.Dto.CountryKeyDto",
  "keyId": 9
}
``` 
Country model is created without CouuntryLocalName (issue 3) and CountryLocalName is NOT validated (Name is required, NameCode should be 5-10 symbols)
### Expected result
CountryLocalName model is validated on request before the Country gets created

**Comment by anna-naumova25** [comment]
### ISSUE 4 No validation for multiple relationship without Keys (ZeroOrMany, OneOrMany)

### Steps to reproduce

1. Add ZeroOrMany relationship to Country entity in SampleWebApp
```
ownedRelationships:
  - name: CountryLocalNameRel
    description: is also know as
    relationship: zeroOrMany
    entity: CountryLocalName
``` 
2. Identify CountryLocalName entity WITHOUT Keys
```
- name: CountryLocalName
  description: The name of a country in other languages

  persistence:
    isAudited: false

  attributes:
    - name: Name
      isRequired: true
      type: text
      textTypeOptions:
        minLength: 5
        maxLength: 10

    - name: NameCode
      isRequired: false
      type: countryCode2
    
    - name: CustomNumber
      isRequired: false
      type: number
      numberTypeOptions:
       minValue: 100
       maxValue: 1000
```  
### Actual result

- yaml file is not validate to check that Keys exist for ZeroOrMany or OneOrMany owned relationships
- the generated files are generated expecting Keys, as a result it leads to build failure

### Expected result
yaml files should be validated so that ZeroOrMany and OneOrMany OwnedRelationship models MUST contain Keys

**Comment by anna-naumova25** [comment]
### ISSUE 5 PostTo[Child] fails because of return type EntityModelDto with only Keys set (ZeroOrMany, OneOrMany)

### Steps to reproduce

1. Add ZeroOrMany relationship to Country entity in SampleWebApp
```
ownedRelationships:
  - name: CountryLocalNameRel
    description: is also know as
    relationship: zeroOrMany
    entity: CountryLocalName
``` 
2. Identify CountryLocalName entity 
```
- name: CountryLocalName
  description: The name of a country in other languages

  persistence:
    isAudited: false

  keys:
    - name: Id
      isRequired: true
      type: databaseNumber

  attributes:
    - name: Name
      isRequired: true
      type: text
      textTypeOptions:
        minLength: 5
        maxLength: 10

    - name: NameCode
      isRequired: false
      type: countryCode2
    
    - name: CustomNumber
      isRequired: false
      type: number
      numberTypeOptions:
       minValue: 100
       maxValue: 1000
```  
3. POST /api/Countries/4/CountryLocalNames
```
{
  "name": "clncln2",
  "nameCode": "FR"
}
``` 
### Actual result

- new CountryLocalName is added to the existing list of CountryLocalNames for Country(4)
- the exception is thrown for the return type CountryLocalNameDto
```
can't parse JSON.  Raw result:

{"@odata.context":"https://localhost:7024/api/$metadata#Countries(10)/CountryLocalNames/$entity","Id":11{"statusCode":500,"message":"Error occured during request: /api/Countries/10/CountryLocalNames.Error: The property \u0027Name[Nullable=False]\u0027 of type \u0027Edm.String\u0027 has a null value, which is not allowed."}
``` 
If happens because we're trying to return CountryLocalNameDto model with only Keys set and OData validation fails for the required properties (Name in this case). This will also reproduce for PatchToCountryLocalName
Need to discuss whether we want to return to CountryLocalNameDto inheritance from CountrlyLocalNameKeyDto to fix it OR if we make another get call to retrun the full CountryLocalNameDto model.
### Expected result
CountryLocalName should be added successfully with the corresponding response

**Comment by anna-naumova25** [comment]
### ISSUE 6 Validation for having at least one child  is missing (OneOrMany)

### Steps to reproduce

1. Add OneOrMany relationship to Country entity in SampleWebApp
```
ownedRelationships:
  - name: CountryLocalNameRel
    description: is also know as
    relationship: oneOrMany
    entity: CountryLocalName
``` 
2. Identify CountryLocalName entity 
```
- name: CountryLocalName
  description: The name of a country in other languages

  persistence:
    isAudited: false

  keys:
    - name: Id
      isRequired: true
      type: databaseNumber

  attributes:
    - name: Name
      isRequired: true
      type: text
      textTypeOptions:
        minLength: 5
        maxLength: 10

    - name: NameCode
      isRequired: false
      type: countryCode2
    
    - name: CustomNumber
      isRequired: false
      type: number
      numberTypeOptions:
       minValue: 100
       maxValue: 1000
```  
3. POST /api/Countries (CountrlyLocalNames is null)
```
{
      "Name": "Name1",
      "FormalName": "FormalName1",
      "AlphaCode3": "MNE",
      "AlphaCode2": "ME",
      "NumericCode": 800,
      "DialingCodes": "DialingCodes11",
      "Capital": "Capital1",
      "Demonym": "Demonym1",
      "AreaInSquareKilometres": 132891.238045,
      "GeoRegion": "qwe",
      "GeoSubRegion": "qwe",
      "GeoWorldRegion": "qwe",
      "Population": 12346,
      "TopLevelDomains": "me",
      "GeoCoord": null
}
``` 
### Actual result
A new country without CountryLocalNames is created successfully
### Expected result
As the relationship type is oneToMany, Country model should be validated to have at least one CountryLocalName
