### ISSUE TITLE
Return OwnedEntityDto from PostTo, PutTo, PatchTo

### ISSUE THREAD

**Issue by anna-naumova25** [NoxOrg/Nox#724]
Issue 5 from #611

### Steps to reproduce

1. Add ZeroOrMany relationship to Country entity in SampleWebApp
```
ownedRelationships:
  - name: CountryLocalNameRel
    description: is also know as
    relationship: zeroOrMany
    entity: CountryLocalName
``` 
2. Identify CountryLocalName entity 
```
- name: CountryLocalName
  description: The name of a country in other languages

  persistence:
    isAudited: false

  keys:
    - name: Id
      isRequired: true
      type: databaseNumber

  attributes:
    - name: Name
      isRequired: true
      type: text
      textTypeOptions:
        minLength: 5
        maxLength: 10

    - name: NameCode
      isRequired: false
      type: countryCode2
    
    - name: CustomNumber
      isRequired: false
      type: number
      numberTypeOptions:
       minValue: 100
       maxValue: 1000
```  
3. POST /api/Countries/4/CountryLocalNames
```
{
  "name": "clncln2",
  "nameCode": "FR"
}
``` 
### Actual result

- new CountryLocalName is added to the existing list of CountryLocalNames for Country(4)
- the exception is thrown for the return type CountryLocalNameDto
```
can't parse JSON.  Raw result:

{"@odata.context":"https://localhost:7024/api/$metadata#Countries(10)/CountryLocalNames/$entity","Id":11{"statusCode":500,"message":"Error occured during request: /api/Countries/10/CountryLocalNames.Error: The property \u0027Name[Nullable=False]\u0027 of type \u0027Edm.String\u0027 has a null value, which is not allowed."}
``` 
If happens because we're trying to return CountryLocalNameDto model with only Keys set and OData validation fails for the required properties (Name in this case). This will also reproduce for PatchToCountryLocalName
Need to discuss whether we want to return to CountryLocalNameDto inheritance from CountrlyLocalNameKeyDto to fix it OR if we make another get call to retrun the full CountryLocalNameDto model.
### Expected result
CountryLocalName should be added successfully with the corresponding response

### Solution
Return the OwnedEntityDto (do an extra query), so we are compliant with Odata
