### ISSUE TITLE
[Nox.Generator] Etag part of SELECT for GET from API on non-Auditable entity

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox#826]
**API GET response**

can't parse JSON.  Raw result:

{"@odata.context":"https://localhost:7231/api/$metadata#Currencies","value":[{"statusCode":500,"message":"Error occured during request: /api/Currencies.Error: Invalid column name \u0027Etag\u0027."}

**Terminal:**

GetCurrenciesQuery handled - response: Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Cryptocash.Application.Dto.CurrencyDto]
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (20ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [c].[Id], [c].[Etag], [c].[ISO_Alpha3], [c].[Name], [c].[Symbol]
      FROM [Currencies] AS [c]
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Cryptocash.Infrastructure.Persistence.DtoDbContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Etag'.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

Entity YAML:
```yaml
#
# Currency.entity.nox.yaml
#

name: Currency

description: Currency definition and related data

keys:

  - name: Id
    isRequired: true
    description: The currency's unique identifier 
    type: text
    textTypeOptions:
        minLength: 3
        maxLength: 5

attributes:

  - name: Name
    description: The currency's name
    type: text
    textTypeOptions:
      minLength: 4
      maxLength: 63
    isRequired: true

  - name: ISO_Alpha3
    description: The currency's official ISO 4217 alpha-3 code
    type: text
    textTypeOptions:
      isUnicode: false
      maxLength: 3
    isRequired: false

  - name: Symbol
    description: The currency's well known symbol
    type: text
    textTypeOptions:
      maxLength: 5

persistence: 
  isAudited: false
  tableName: Currency
  schema: dbo

  create:
    isEnabled: true
    raiseEvents: false

  read:
    isEnabled: true

  update:
    isEnabled: true
    raiseEvents: false

  delete:
    isEnabled: true
    raiseEvents: false 
```
