### ISSUE TITLE
[Nox.Lib] Add To Custom IE the EventTypeAttribute

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#926]
- relates to #799 

## Custom IE, Trait and Event name

1. Add a Trait (string type), required to the integration events in Nox.Solution
2. Update the Custom Integration Event Template and add the integration event attribute, example

  ```
     [IntegrationEvent("PopulationHigherThan","Country")]
     public record PopulationHigherThan(...): IIntegrationEvent;    
```

Nox.Solution example:

```
application:
  integrationEvents:
        - name: PopulationHigherThan
          type: object
          trait: Country
          objectTypeOptions:
            attributes:
              - name: CountryId
                type: countryCode2

              - name: CountryName
                type: text

              - name: Population
                type: number
```
