### ISSUE TITLE
[Nox.Types] Enum Type - Parent Issue

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox#988]
# Enum Nox Type

## Data Model
- #996
- #1018 
### Entity Model

Create two Additional models (EF) for each Enum Type attribute found, one for keeping the values the other the translations (if "isLocalized=true"):

```
  public class <AttributeName>Enum: IEntityConcurrent
  {    
      public number Id { get; set; } // Primary key for enum value
      public text Name { get; set;} //Enum name default translation - Required
  }

public class <AttributeName>EnumLocalized: IEntityConcurrent
  {    
      public number Id { get; set; } // Primary key & ForeignKey
      public CultureCode CultureCode { get; set; } // Primary Key
      public text Name { get; set;} //Enum name default translation Required
  }
```

### Db Configuration
Each entity enum attribute must:
  - Configure property type as int
  - Set foreign key to `<AttributeName>Enum`

Each enum must:
 - Configure Primary key for both  `<AttributeName>Enum` and  `<AttributeName>EnumLocalized`
 - Configure Foreign Keys
 - Add DbSet to entityDbContext

`
## Generator
- #1002 
 1. (Validate its working as expected)Dto / UpdateDto / CreateDto contains the respective property 
     2. (Read)Dto Add additional property `<AttributeName>Name` that will return the translated name of the enum value (Default value if not found between square brackets)
 3. (Validate its working as expected)Add support to Metadata to create this type with the corresponding type options
 
## Seed Values
- #1017
When the API start the Default Values must be created or updated, do not delete other values, this is a service responsible to know how to manage this cases

## OData API
- #1021
The `<Entity>Dto` has a property named `<AttributeName>Name` for enum types to hold the translated enum value

Update Get and GetById for entities with enum types:

1. Get the request language from the header, fall back to default language in Nox.Solution if not found, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
   1. Use the new template for the API, migrate this method to the new template first (Create a PR just with this)  
3. The Entity `<EntityName><AttributeName>Localized` contains the translations data for enums, default one will always exist
4. Update Get\<Entity\>Query to receive a culture code if contains a localized field 
5. Update Get\<Entity\>Query  update the IQueryable to return the proper translated enum value according to the culturecode   
  1. Generate SQL for all columns and localized columns, if no localized columns keep as it is no changed if needed
6. if no translation is found return default between square brackets "[Default name]"
1. Ensure to have tests on the client API and Integration Tests asserting the localized data is correct

Apply the same solution and learnings #937 

## Translations for an Enum,
- #1022

Have a endpoint for each localized entity with (in the Entity Controller):
1. GET  `/api/<PluralEntityName>/<AttributName>/` => List enum values with **Name translated**

### Manage Translations
- #1024
Have a endpoint for each localized entity  with (in the Entity Controller):

1. GET  `/api/<PluralEntityName>/<AttributName>Localized/` => List enum names translations
3. DELETE, Put, Post ` /api/<PluralEntityName>/<AttributName>Localized` => delete/updates/create a new enum name translation 
   4. If creating, set also the name, even if not the default culture and create entry in localized table also
   5. If updating default culture also update `<AttributName>Enum`
   9. Can not delete Default Culture
   10. The Get have OData EnableQuery =>  with filtering and select capabilities

# Concepts that are not in Scope

1. Auditable
1. Soft Delete

# Trade offs to be accepted for now

1. Expand Entities will return default culture translations

## Examples 

  ```
- name: Status
    description: The status of a workplace
    type: enum
    enumTypeOptions:
      idPrimitiveType: integer      # default to "defaultValues[0].id or 'integer' if not specified
      defaultValues:  # optional     # (should not specify these here if CanUpdate=true)
        - { id: 0, description: "Opening" }   # The persistence table will be IAuditable (soft deleted, etc..)
        - { id: 1, description: "Open" } 
        - { id: 2, description: "Closed" }  
        # api created : { 3, description: "new" }
      isLocalized: true       # default true
      multiState: false       # default false
      canUpdate: true  # default false
    isRequired: true         # default false
 
  - name: ApplicationStatus
    description: The status of a workplace
    type: enum
    enumTypeOptions:
      idPrimitiveType: integer
      defaultValues:  
        - { id: 0, description: "Sent" } 
        - { id: 1, description: "Opened" } 
        - { id: 2, description: "Signed" }
        - { id: 3, description: "Closed" }
      isLocalized: false
      multiState: true
      canUpdate: false
    isRequired: false
 
  - name: LeaseStatus
    description: The status of a lease contract for a worklplace
    type: enum
    enumTypeOptions:
      defaultValues:  
        - { id: 'D', description: "Drafted" } 
        - { id: 'R', description: "Reviewed" } 
        - { id: 'S', description: "Signed" }
        - { id: 'C', description: "Completed" }
      isLocalized: false
      multiState: true
      canUpdate: false
    isRequired: false
 
  - name: CleaningStatus
    description: The status of a lease contract for a worklplace
    type: enum
    enumTypeOptions:
      idPrimitiveType: integer # (if not specified, integer is the default)
      isLocalized: true
      multiState: false
      canUpdate: true
    isRequired: false

```
